version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r app/requirements.txt
      - pip install pytest
      - python --version
      - pip list  # Show installed packages
  
  build:
    commands:
      - ls -R  # Show directory structure
      - pwd    # Show current directory
      - export PYTHONPATH=$(pwd)
      - python -c "import sys; print(sys.path)"  # Print Python path
      - pytest -v test/ --junitxml=report.xml -s  # Add -s for more verbose output
  
  post_build:
    commands:
      - echo "Build and test complete."

reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: ./

artifacts:
  files:
    - '**/*'
  name: myproject-$(date +%Y-%m-%d-%H-%M-%S).zip
  base-directory: '.'
