version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r app/requirements.txt
      - pip install pytest 
      - python --version
      - pip list
  build:
    commands:
      - ls -R
      - pwd
      - export PYTHONPATH=$(pwd)  # Add the current directory to PYTHONPATH
      - python -c "import sys; print(sys.path)"
      - echo $PYTHONPATH
      - pytest -v test/ --junitxml=report.xml
  post_build:
    commands:
      - echo "Build and test complete."

reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: ./
