version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r app/requirements.txt
      - pip install pytest
  build:
    commands:
      - ls -R
      - pytest test/ --junitxml=report.xml
  post_build:
    commands:
      - echo "Build and test complete."

reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: ./
